//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKY.NgonNgu {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages_vn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages_vn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IKY.NgonNgu.Messages_vn", typeof(Messages_vn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn thoát khỏi chương trình.
        /// </summary>
        internal static string BanCoChacMuonThoat {
            get {
                return ResourceManager.GetString("BanCoChacMuonThoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình SQL server không thành công.
        /// </summary>
        internal static string CauHinhSQLServerKhongThanhCong {
            get {
                return ResourceManager.GetString("CauHinhSQLServerKhongThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi không cập nhật được thông tin..
        /// </summary>
        internal static string ChucVuUpdateError {
            get {
                return ResourceManager.GetString("ChucVuUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi kết nối cổng COM. Vui lòng kiểm tra lại.
        /// </summary>
        internal static string ComPortError {
            get {
                return ResourceManager.GetString("ComPortError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên Tablespace..
        /// </summary>
        internal static string ConfigTablespaceBlank {
            get {
                return ResourceManager.GetString("ConfigTablespaceBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng kiểm tra lại User, Tên user không tồn tại..
        /// </summary>
        internal static string ConfigUserNotExist {
            get {
                return ResourceManager.GetString("ConfigUserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database tạo không thành công.
        /// </summary>
        internal static string DatabaseTaoKhongThanhCong {
            get {
                return ResourceManager.GetString("DatabaseTaoKhongThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID thẻ không hợp lệ.
        /// </summary>
        internal static string IDTheBHKhongHopLe {
            get {
                return ResourceManager.GetString("IDTheBHKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông số sẽ khởi tạo lại trạng thái ban đầu. Bạn có đồng ý khởi tạo lại thông số không?.
        /// </summary>
        internal static string KhoiTaoThongSoQuestion {
            get {
                return ResourceManager.GetString("KhoiTaoThongSoQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không phát sinh lỗi..
        /// </summary>
        internal static string KhongLoi {
            get {
                return ResourceManager.GetString("KhongLoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số thẻ không hợp lệ.
        /// </summary>
        internal static string SoTheBHKhongHopLe {
            get {
                return ResourceManager.GetString("SoTheBHKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết nối dữ liệu bị lỗi..
        /// </summary>
        internal static string TestKetNoiLoi {
            get {
                return ResourceManager.GetString("TestKetNoiLoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi lưu dữ liệu. Vui lòng thử lại.
        /// </summary>
        internal static string UpdateError {
            get {
                return ResourceManager.GetString("UpdateError", resourceCulture);
            }
        }
    }
}
